#release configuration
#Fri Jan 09 01:37:13 PST 2026
completedPhase=generate-release-poms
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.com.hellblazer.delos\:choam=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:cryptography=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:delos.app=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:delphinius=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:domain-epoll=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:domain-kqueue=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:domain-sockets=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:ethereal=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:examples=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:fireflies=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:gorgoneion=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:gorgoneion-client=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:grpc=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:h2-deterministic=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:java-noise=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:leyden=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:liquibase-deterministic=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:local-demo=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:memberships=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:model=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:protocols=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:schemas=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:simple-kv-store=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:sql-state=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:stereotomy=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:stereotomy-services=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:thoth=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:tron=0.0.7-SNAPSHOT
project.dev.com.hellblazer.delos\:vm-socket=0.0.7-SNAPSHOT
project.rel.com.hellblazer.delos\:choam=0.0.6
project.rel.com.hellblazer.delos\:cryptography=0.0.6
project.rel.com.hellblazer.delos\:delos.app=0.0.6
project.rel.com.hellblazer.delos\:delphinius=0.0.6
project.rel.com.hellblazer.delos\:domain-epoll=0.0.6
project.rel.com.hellblazer.delos\:domain-kqueue=0.0.6
project.rel.com.hellblazer.delos\:domain-sockets=0.0.6
project.rel.com.hellblazer.delos\:ethereal=0.0.6
project.rel.com.hellblazer.delos\:examples=0.0.6
project.rel.com.hellblazer.delos\:fireflies=0.0.6
project.rel.com.hellblazer.delos\:gorgoneion=0.0.6
project.rel.com.hellblazer.delos\:gorgoneion-client=0.0.6
project.rel.com.hellblazer.delos\:grpc=0.0.6
project.rel.com.hellblazer.delos\:h2-deterministic=0.0.6
project.rel.com.hellblazer.delos\:java-noise=0.0.6
project.rel.com.hellblazer.delos\:leyden=0.0.6
project.rel.com.hellblazer.delos\:liquibase-deterministic=0.0.6
project.rel.com.hellblazer.delos\:local-demo=0.0.6
project.rel.com.hellblazer.delos\:memberships=0.0.6
project.rel.com.hellblazer.delos\:model=0.0.6
project.rel.com.hellblazer.delos\:protocols=0.0.6
project.rel.com.hellblazer.delos\:schemas=0.0.6
project.rel.com.hellblazer.delos\:simple-kv-store=0.0.6
project.rel.com.hellblazer.delos\:sql-state=0.0.6
project.rel.com.hellblazer.delos\:stereotomy=0.0.6
project.rel.com.hellblazer.delos\:stereotomy-services=0.0.6
project.rel.com.hellblazer.delos\:thoth=0.0.6
project.rel.com.hellblazer.delos\:tron=0.0.6
project.rel.com.hellblazer.delos\:vm-socket=0.0.6
project.scm.com.hellblazer.delos\:choam.empty=true
project.scm.com.hellblazer.delos\:cryptography.empty=true
project.scm.com.hellblazer.delos\:delos.app.connection=scm\:git\:https\://github.com/Hellblazder/delos.git
project.scm.com.hellblazer.delos\:delos.app.developerConnection=scm\:git\:https\://github.com/Hellblazer/delos.git
project.scm.com.hellblazer.delos\:delos.app.tag=HEAD
project.scm.com.hellblazer.delos\:delos.app.url=https\://https\://github.com/Hellblazer/delos
project.scm.com.hellblazer.delos\:delphinius.empty=true
project.scm.com.hellblazer.delos\:domain-epoll.empty=true
project.scm.com.hellblazer.delos\:domain-kqueue.empty=true
project.scm.com.hellblazer.delos\:domain-sockets.empty=true
project.scm.com.hellblazer.delos\:ethereal.empty=true
project.scm.com.hellblazer.delos\:examples.empty=true
project.scm.com.hellblazer.delos\:fireflies.empty=true
project.scm.com.hellblazer.delos\:gorgoneion-client.empty=true
project.scm.com.hellblazer.delos\:gorgoneion.empty=true
project.scm.com.hellblazer.delos\:grpc.empty=true
project.scm.com.hellblazer.delos\:h2-deterministic.empty=true
project.scm.com.hellblazer.delos\:java-noise.empty=true
project.scm.com.hellblazer.delos\:leyden.empty=true
project.scm.com.hellblazer.delos\:liquibase-deterministic.empty=true
project.scm.com.hellblazer.delos\:local-demo.empty=true
project.scm.com.hellblazer.delos\:memberships.empty=true
project.scm.com.hellblazer.delos\:model.empty=true
project.scm.com.hellblazer.delos\:protocols.empty=true
project.scm.com.hellblazer.delos\:schemas.empty=true
project.scm.com.hellblazer.delos\:simple-kv-store.empty=true
project.scm.com.hellblazer.delos\:sql-state.empty=true
project.scm.com.hellblazer.delos\:stereotomy-services.empty=true
project.scm.com.hellblazer.delos\:stereotomy.empty=true
project.scm.com.hellblazer.delos\:thoth.empty=true
project.scm.com.hellblazer.delos\:tron.empty=true
project.scm.com.hellblazer.delos\:vm-socket.empty=true
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=delos.app-0.0.6
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/Hellblazer/delos.git
