/*
 * Copyright (c) 2025 Hal Hildebrand. All rights reserved.
 */

package com.hellblazer.delos.cryptography.bls;

import java.util.Arrays;
import java.util.Objects;

/**
 * Proof of Possession for BLS public keys.
 * <p>
 * A Proof of Possession (PoP) is a signature over the public key itself,
 * which prevents rogue key attacks in BLS signature aggregation.
 * <p>
 * The PoP is generated by signing the public key with the corresponding secret key:
 * PoP = Sign(secretKey, publicKey)
 * <p>
 * Verification checks that the PoP is a valid signature of the public key:
 * Verify(publicKey, PoP, publicKey)
 *
 * @param compressedSignature The PoP signature (48 bytes compressed)
 * @author hal.hildebrand
 */
public record ProofOfPossession(byte[] compressedSignature) {
    /**
     * Size of a compressed PoP signature (G1 point)
     */
    public static final int COMPRESSED_SIZE = 48;

    /**
     * Compact constructor with validation and defensive copy.
     *
     * @throws NullPointerException     if compressedSignature is null
     * @throws IllegalArgumentException if compressedSignature is not COMPRESSED_SIZE bytes
     */
    public ProofOfPossession {
        Objects.requireNonNull(compressedSignature, "compressedSignature cannot be null");
        if (compressedSignature.length != COMPRESSED_SIZE) {
            throw new IllegalArgumentException(
                "PoP must be " + COMPRESSED_SIZE + " bytes, got " + compressedSignature.length);
        }
        // Defensive copy
        compressedSignature = compressedSignature.clone();
    }

    /**
     * Generate a Proof of Possession for a public key.
     * <p>
     * Signs the public key bytes with the secret key to create the PoP.
     *
     * @param secretKey      Secret key to sign with
     * @param publicKeyBytes Public key bytes to sign over (96 bytes)
     * @param provider       BLS provider for signing
     * @return Generated Proof of Possession
     */
    public static ProofOfPossession generate(BLSSecretKey secretKey, byte[] publicKeyBytes, BLSProvider provider) {
        Objects.requireNonNull(secretKey, "secretKey cannot be null");
        Objects.requireNonNull(publicKeyBytes, "publicKeyBytes cannot be null");
        Objects.requireNonNull(provider, "provider cannot be null");

        // Sign the public key with the secret key
        var signature = secretKey.sign(publicKeyBytes);
        return new ProofOfPossession(signature.compressedBytes());
    }

    /**
     * Verify this Proof of Possession against a public key.
     * <p>
     * Checks that this PoP is a valid signature of the public key by the
     * corresponding secret key.
     *
     * @param publicKeyBytes Public key bytes (96 bytes)
     * @param provider       BLS provider for verification
     * @return true if PoP is valid, false otherwise
     */
    public boolean verify(byte[] publicKeyBytes, BLSProvider provider) {
        Objects.requireNonNull(publicKeyBytes, "publicKeyBytes cannot be null");
        Objects.requireNonNull(provider, "provider cannot be null");

        // Verify that the PoP is a valid signature of the public key
        return provider.verify(publicKeyBytes, publicKeyBytes, compressedSignature);
    }

    /**
     * Get the compressed signature bytes (defensive copy).
     *
     * @return A copy of the signature bytes
     */
    @Override
    public byte[] compressedSignature() {
        return compressedSignature.clone();
    }

    /**
     * Equality based on signature bytes.
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!(obj instanceof ProofOfPossession other)) return false;
        return Arrays.equals(compressedSignature, other.compressedSignature);
    }

    /**
     * Hash code based on signature bytes.
     */
    @Override
    public int hashCode() {
        return Arrays.hashCode(compressedSignature);
    }

    @Override
    public String toString() {
        return "ProofOfPossession[" + compressedSignature.length + " bytes]";
    }
}

